package fastvpn

// countryNames maps the ISO-3166 alpha-2 codes that appear in
// FastVPN's NCVPN-<CC>-... config filenames to canonical English
// country names. Generated from the codes present in the upstream
// vpn.ncapi.io/groupedServerList.zip (UDP subset). Any code not
// listed here falls through to the bare CC in fastvpn.go's
// loadServers — safe degradation, just less pretty Locations()
// output.
//
// FastVPN uses "UK" for the United Kingdom rather than "GB".

func countryName(cc string) (string, bool) {
	n, ok := countryNames[cc]
	return n, ok
}

var countryNames = map[string]string{
	"AD": "Andorra",
	"AE": "United Arab Emirates",
	"AL": "Albania",
	"AM": "Armenia",
	"AR": "Argentina",
	"AT": "Austria",
	"AU": "Australia",
	"AZ": "Azerbaijan",
	"BA": "Bosnia and Herzegovina",
	"BD": "Bangladesh",
	"BE": "Belgium",
	"BG": "Bulgaria",
	"BM": "Bermuda",
	"BN": "Brunei",
	"BO": "Bolivia",
	"BR": "Brazil",
	"BS": "Bahamas",
	"BT": "Bhutan",
	"BZ": "Belize",
	"CA": "Canada",
	"CH": "Switzerland",
	"CL": "Chile",
	"CO": "Colombia",
	"CR": "Costa Rica",
	"CY": "Cyprus",
	"CZ": "Czech Republic",
	"DE": "Germany",
	"DK": "Denmark",
	"DO": "Dominican Republic",
	"DZ": "Algeria",
	"EC": "Ecuador",
	"EE": "Estonia",
	"EG": "Egypt",
	"ES": "Spain",
	"FI": "Finland",
	"FR": "France",
	"GE": "Georgia",
	"GH": "Ghana",
	"GR": "Greece",
	"GT": "Guatemala",
	"HK": "Hong Kong",
	"HN": "Honduras",
	"HR": "Croatia",
	"HT": "Haiti",
	"HU": "Hungary",
	"ID": "Indonesia",
	"IE": "Ireland",
	"IL": "Israel",
	"IM": "Isle of Man",
	"IN": "India",
	"IS": "Iceland",
	"IT": "Italy",
	"JE": "Jersey",
	"JM": "Jamaica",
	"JO": "Jordan",
	"JP": "Japan",
	"KE": "Kenya",
	"KH": "Cambodia",
	"KR": "South Korea",
	"KY": "Cayman Islands",
	"KZ": "Kazakhstan",
	"LA": "Laos",
	"LB": "Lebanon",
	"LI": "Liechtenstein",
	"LK": "Sri Lanka",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"LV": "Latvia",
	"MA": "Morocco",
	"MC": "Monaco",
	"MD": "Moldova",
	"ME": "Montenegro",
	"MK": "Macedonia",
	"MM": "Myanmar",
	"MN": "Mongolia",
	"MO": "Macao",
	"MT": "Malta",
	"MX": "Mexico",
	"MY": "Malaysia",
	"NG": "Nigeria",
	"NI": "Nicaragua",
	"NL": "Netherlands",
	"NO": "Norway",
	"NP": "Nepal",
	"NZ": "New Zealand",
	"PA": "Panama",
	"PE": "Peru",
	"PG": "Papua New Guinea",
	"PH": "Philippines",
	"PK": "Pakistan",
	"PL": "Poland",
	"PR": "Puerto Rico",
	"PT": "Portugal",
	"PY": "Paraguay",
	"RO": "Romania",
	"RS": "Serbia",
	"SA": "Saudi Arabia",
	"SE": "Sweden",
	"SG": "Singapore",
	"SI": "Slovenia",
	"SK": "Slovakia",
	"TH": "Thailand",
	"TR": "Turkey",
	"TT": "Trinidad and Tobago",
	"TW": "Taiwan",
	"UA": "Ukraine",
	"UK": "United Kingdom",
	"US": "United States",
	"UY": "Uruguay",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"ZA": "South Africa",
}
